import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";
import { redirect } from "next/navigation";
import dbConnect from "@/lib/db";
import { Booking } from "@/models/Booking";
import { Train } from "@/models/Train";
import mongoose from "mongoose";

export const dynamic = 'force-dynamic';

export default async function RevenueAnalyticsPage() {
  const session = await getServerSession(authOptions);
  if (!session || (session.user as any).role !== "admin") redirect("/admin/login");

  await dbConnect();
  
  if (!mongoose.models.Train) mongoose.model('Train', Train.schema);

  const revenueByTrain = await Booking.aggregate([
    { $match: { status: 'CONFIRMED' } },
    { $group: { _id: '$trainId', totalRevenue: { $sum: '$pricePaid' }, bookings: { $sum: 1 } } },
    { $sort: { totalRevenue: -1 } },
    { $lookup: { from: 'trains', localField: '_id', foreignField: '_id', as: 'train' } },
    { $unwind: { path: '$train', preserveNullAndEmptyArrays: true } }
  ]);

  const totalRevenue = revenueByTrain.reduce((acc, curr) => acc + curr.totalRevenue, 0);

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-black text-slate-900 tracking-tight">Revenue Analytics</h1>
        <p className="text-slate-500 font-medium mt-1">Detailed breakdown of total revenue generated by trains.</p>
      </div>
      
      <div className="bg-emerald-50 border border-emerald-100 rounded-[2rem] p-8 flex flex-col justify-center items-center text-center shadow-sm">
        <p className="text-emerald-700 font-bold uppercase tracking-wider mb-2">Total System Revenue</p>
        <p className="text-5xl font-black text-emerald-600">₹{totalRevenue.toLocaleString('en-IN')}</p>
      </div>

      <div className="bg-white border border-slate-200 rounded-3xl overflow-hidden shadow-sm max-h-[calc(100vh-200px)] overflow-y-auto">
        <div className="overflow-x-auto">
          <table className="w-full text-left whitespace-nowrap">
            <thead className="bg-slate-50 border-b border-slate-200 sticky top-0 z-10">
              <tr>
                <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase">Rank</th>
                <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase">Train</th>
                <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase text-right">Confirmed Bookings</th>
                <th className="px-6 py-4 text-xs font-bold text-slate-500 uppercase text-right">Revenue Generated</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {revenueByTrain.map((item, idx) => (
                <tr key={item._id.toString()} className="hover:bg-slate-50 transition-colors">
                  <td className="px-6 py-4 font-black text-slate-400">#{idx + 1}</td>
                  <td className="px-6 py-4">
                    <div className="font-bold text-slate-900">{item.train?.name || "Unknown Train"}</div>
                    <div className="text-xs font-medium text-slate-500">Train No. {item.train?.trainNumber || "N/A"}</div>
                  </td>
                  <td className="px-6 py-4 text-right font-bold text-slate-700">{item.bookings}</td>
                  <td className="px-6 py-4 text-right font-black text-emerald-600">₹{item.totalRevenue.toLocaleString('en-IN')}</td>
                </tr>
              ))}
              {revenueByTrain.length === 0 && (
                <tr>
                  <td colSpan={4} className="px-6 py-12 text-center text-slate-500 font-medium">No revenue generated yet.</td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
